# Generated by Django 4.2.5 on 2023-10-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "payment_option",
                    models.CharField(
                        choices=[
                            ("Rental", "Rental"),
                            ("HirePurchase", "HirePurchase"),
                            ("Buy", "Buy"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "equipment_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.catalogue",
                    ),
                ),
            ],
        ),
    ]
