# Generated by Django 4.2.5 on 2023-09-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HirePurchase',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
