# Generated by Django 4.2.5 on 2023-09-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payment_option_alter_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='equipment_name',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('Rental', 'Rental'), ('HirePurchase', 'HirePurchase'), ('Buy', 'Buy')], max_length=20),
        ),
    ]
