# Generated by Django 4.2.5 on 2023-09-25 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_rename_data_work_payment_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="data",
            new_name="date",
        ),
    ]
