# Generated by Django 4.2.5 on 2023-10-03 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_alter_category_dairy_alter_category_farm_and_more"),
        ("payments", "0008_rename_data_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="equipment_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.catalogue",
            ),
            preserve_default=False,
        ),
    ]
