# Generated by Django 4.2.5 on 2023-10-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_alter_category_dairy_alter_category_farm_and_more"),
        ("payments", "0010_alter_payment_equipment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="equipment_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="category.catalogue"
            ),
        ),
    ]
