name: Django Build and Test CICD
on:
  push:
    branches:
      - main
      - dev
      - staging
  pull_request:
    branches:
      - main
      - dev
      - staging
  jobs:
  build:
    runs-on: ubuntu-20.04
        steps:
      - name: Checkout code
        uses: actions/checkout@v2      
        - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'      
        #   - name: Install Dependencies
        # run: |
        #   - pip install -r requirements.txt      
        #   - name: Format Code with pre-commit
        # run: |
        #   pip install pre-commit
        #   pre-commit run --all-files      
        #   - name: Make Migrations
        # run: |
        #   python manage.py makemigrations      
        #   - name: Migration
        # run: |
        #   python3 manage.py migrate      
        #   - name: Run server
        # run: |
        #   python3 manage.py runserver      
        #   - name: Run Tests
        # run: |
        #   python manage.py test


