# Generated by Django 4.2.5 on 2023-10-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rentals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rental_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rental_period", models.DurationField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "duration_period",
                    models.CharField(
                        choices=[("week", "Week"), ("day", " Day")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "total_rental_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "equipment_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.catalogue",
                    ),
                ),
            ],
        ),
    ]
