# Generated by Django 4.2.5 on 2023-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0003_alter_rentals_total_rental_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='duration_period',
            field=models.CharField(choices=[('week', 'Week'), ('day', 'Day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='rental_period',
            field=models.DurationField(),
        ),
    ]
