# Generated by Django 4.2.5 on 2023-09-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date_time', models.DateTimeField()),
                ('validity_period', models.TimeField()),
                ('payment_balance', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
    ]
