# Generated by Django 4.2.5 on 2023-09-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_transaction_id_alter_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='payment_date_time',
        ),
    ]
