# Generated by Django 4.2.5 on 2023-10-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farm",
                    models.CharField(
                        choices=[
                            ("plow", "Plow"),
                            ("harrow", "Harrow"),
                            ("planter", "Planter"),
                            ("tractor", "Tractor"),
                            ("combined harvester", "Combined Harvester"),
                            ("planter", "Planter"),
                            ("hay baler", "Hay-baler"),
                        ],
                        default="plow",
                        max_length=20,
                    ),
                ),
                (
                    "poultry",
                    models.CharField(
                        choices=[
                            ("nesting_boxes", "Nesting_boxes"),
                            ("egg_incubators", "Egg_incubators"),
                            ("automatic_waterers", "Automatic_waterers"),
                            ("chicken_coop", "Chicken_coop"),
                            ("brooder_lamp", "Brooder_lamp"),
                        ],
                        default="nesting_boxes",
                        max_length=20,
                    ),
                ),
                (
                    "dairy",
                    models.CharField(
                        choices=[
                            ("milking_machine", "Milking-machine"),
                            ("milk_pasteurizer", "Milk_pasteurizer"),
                            ("cow_brushes", "Cow_brushes"),
                            ("testing_equipment", "Testing_equipment"),
                            ("milk_cooler", "Milk_cooler"),
                            ("cream_separator", "Cream_separator"),
                            ("cheese_vat", "Cheese_vat"),
                        ],
                        default="milking_machine",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Catalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_name", models.CharField(max_length=32, unique=True)),
                ("price", models.IntegerField()),
                ("description", models.TextField(null=True)),
                ("image", models.ImageField(null=True, upload_to="catalogue_images/")),
                ("is_available", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
            ],
        ),
    ]
