# Generated by Django 4.2.5 on 2023-10-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogue",
            name="image",
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
