# Generated by Django 4.2.5 on 2023-10-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_catalogue_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogue",
            name="in_stock",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
