# Generated by Django 4.2.5 on 2023-09-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_category_poultry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_name", models.CharField(max_length=32, unique=True)),
                ("price", models.IntegerField()),
                ("description", models.TextField(null=True)),
                ("image", models.ImageField(null=True, upload_to="catalogue_images/")),
                ("is_available", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
            ],
        ),
    ]
