# Generated by Django 4.2.5 on 2023-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hirepurchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirepurchase',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hirepurchase',
            name='equipment_name',
            field=models.CharField(max_length=100),
        ),
    ]
