# Generated by Django 4.2.5 on 2023-09-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hirepurchase', '0002_alter_hirepurchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirepurchase',
            name='equipment_name',
        ),
    ]
