# Generated by Django 4.2.5 on 2023-09-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0006_alter_catalogue_category_alter_catalogue_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogue",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
