# Generated by Django 4.2.5 on 2023-09-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0009_catalogue_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogue",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
