# Generated by Django 4.2.5 on 2023-09-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0011_alter_catalogue_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catalogue",
            old_name="Equipment_name",
            new_name="equipment_name",
        ),
    ]
