# Generated by Django 4.2.5 on 2023-10-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HirePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("down_payment", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("installment_period", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                            ("semi_annually", "Semi-Annually"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipment_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.catalogue",
                    ),
                ),
            ],
        ),
    ]
