# Generated by Django 4.2.5 on 2023-09-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_alter_catalogue_options_alter_catalogue_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogue",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
