# Generated by Django 4.2.5 on 2023-09-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_alter_catalogue_id_alter_catalogue_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("detail", models.TextField()),
                ("image", models.ImageField(upload_to="catalogue_images/")),
            ],
            options={
                "verbose_name_plural": "2. Categories",
            },
        ),
        migrations.AddField(
            model_name="catalogue",
            name="price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="image",
            field=models.ImageField(null=True, upload_to="catalogue_images/"),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.category",
            ),
        ),
    ]
