# Generated by Django 4.2.5 on 2023-09-21 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0005_category_catalogue_price_alter_catalogue_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogue",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.category",
            ),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="image",
            field=models.ImageField(null=True, upload_to="catalogue_images/"),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
