# Generated by Django 4.2.5 on 2023-09-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0005_category_catalogue_price_alter_catalogue_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogue",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
