# Generated by Django 4.2.5 on 2023-09-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_remove_catalogue_category_delete_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("detail", models.TextField()),
                ("image", models.ImageField(upload_to="catalogue_images/")),
                ("datecreated", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "2. Categories",
            },
        ),
        migrations.AddField(
            model_name="catalogue",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.category",
            ),
        ),
    ]
