# Generated by Django 4.2.5 on 2023-09-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0013_rename_equipment_name_catalogue_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogue",
            options={"verbose_name_plural": "catalog"},
        ),
    ]
