# Generated by Django 4.2.5 on 2023-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_delete_hirepurchase_delete_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('Rental', 'Rental'), ('HirePurchase', 'HirePurchase'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
