# Generated by Django 4.2.5 on 2023-09-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_remove_payment_equipment_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_option",
            field=models.CharField(
                choices=[
                    ("Rental", "Rental"),
                    ("HirePurchase", "HirePurchase"),
                    ("Buy", "Buy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
