# Generated by Django 4.2.5 on 2023-09-25 00:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_alter_payment_payment_option"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="date",
            new_name="data_work",
        ),
    ]
