# Generated by Django 4.2.3 on 2023-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_farmer_supplier_delete_user_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
