# Generated by Django 4.2.3 on 2023-09-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_farmer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
