# Generated by Django 4.2.3 on 2023-09-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_farmer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='crops_grown',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='farm_size',
        ),
        migrations.AddField(
            model_name='farmer',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
