# Generated by Django 4.2.3 on 2023-09-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_farmer_crops_grown_remove_farmer_farm_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
