# Generated by Django 4.2.5 on 2023-10-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField(max_length=2000, null=True)),
                ("duration", models.DurationField()),
                ("customer_name", models.CharField(default="Customer", max_length=255)),
                (
                    "equipment_name",
                    models.CharField(default="Default Equipment", max_length=32),
                ),
                (
                    "equipment_category",
                    models.CharField(default="Default Category", max_length=32),
                ),
                ("booking_date", models.DateTimeField()),
                ("date_returned", models.DateTimeField(blank=True, null=True)),
                (
                    "phone_number",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.customuser",
                    ),
                ),
            ],
        ),
    ]
