# Generated by Django 4.2.5 on 2023-10-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="date_returned",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="image",
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
