# Generated by Django 4.2.5 on 2023-10-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="image",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
    ]
