# Generated by Django 4.2.5 on 2023-10-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0003_alter_bookings_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="image",
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
