# Generated by Django 4.2.5 on 2023-10-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0004_alter_bookings_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="image",
            new_name="upload_image",
        ),
    ]
