# Generated by Django 4.2.5 on 2023-10-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_alter_customuser_managers_alter_farmer_user_and_more"),
        ("Bookings", "0007_bookings_date_returned"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="phone_number",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="register.customuser",
            ),
            preserve_default=False,
        ),
    ]
