# Generated by Django 4.2.5 on 2023-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0002_remove_bookings_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="customer_name",
            field=models.CharField(default="Customer", max_length=255),
        ),
        migrations.AddField(
            model_name="bookings",
            name="equipment_category",
            field=models.CharField(default="Default Category", max_length=32),
        ),
        migrations.AddField(
            model_name="bookings",
            name="equipment_name",
            field=models.CharField(default="Default Equipment", max_length=32),
        ),
    ]
