# Generated by Django 4.2.3 on 2023-09-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_bookings_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='customer_id',
        ),
    ]
