# Generated by Django 4.2.5 on 2023-09-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_period', models.DurationField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_option', models.CharField(choices=[('week', 'Week'), ('one_day', 'One Day')], max_length=20)),
                ('total_rental_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
