# Generated by Django 4.2.5 on 2023-09-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='rentals',
            name='duration_period',
            field=models.CharField(choices=[('week', 'Week'), ('day', ' Day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='total_rental_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
