# Generated by Django 4.2.5 on 2023-09-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0004_alter_rentals_date_alter_rentals_duration_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='equipment_name',
        ),
        migrations.AlterField(
            model_name='rentals',
            name='duration_period',
            field=models.CharField(choices=[('week', 'Week'), ('day', ' Day')], max_length=20, null=True),
        ),
    ]
