# Generated by Django 4.2.5 on 2023-09-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.RemoveField(
            model_name="category",
            name="detail",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="title",
        ),
        migrations.AddField(
            model_name="category",
            name="dairy",
            field=models.CharField(
                choices=[
                    ("milking_machine", "Milking-machine"),
                    ("milk_pasteurizer", "Milk_pasteurizer"),
                    ("cow_brushes", "Cow_brushes"),
                    ("testing_equipment", "Testing_equipment"),
                ],
                default="milking_machine",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="farm",
            field=models.CharField(
                choices=[
                    ("plow", "Plow"),
                    ("harrow", "Harrow"),
                    ("planter", "Planter"),
                ],
                default="plow",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="poultry",
            field=models.CharField(
                choices=[
                    ("nesting_boxes", "Nesting_boxes"),
                    ("egg_incubators", "Egg_incubators"),
                    ("automatic_waterers", "Automatic_waterers"),
                ],
                default=2,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
