# Generated by Django 4.2.5 on 2023-09-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_options_remove_category_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="poultry",
            field=models.CharField(
                choices=[
                    ("nesting_boxes", "Nesting_boxes"),
                    ("egg_incubators", "Egg_incubators"),
                    ("automatic_waterers", "Automatic_waterers"),
                ],
                default="nesting_boxes",
                max_length=20,
            ),
        ),
    ]
