# Generated by Django 4.2.5 on 2023-09-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_catalogue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="dairy",
            field=models.CharField(
                choices=[
                    ("milking_machine", "Milking-machine"),
                    ("milk_pasteurizer", "Milk_pasteurizer"),
                    ("cow_brushes", "Cow_brushes"),
                    ("testing_equipment", "Testing_equipment"),
                    ("milk_cooler", "Milk_cooler"),
                    ("cream_separator", "Cream_separator"),
                    ("cheese_vat", "Cheese_vat"),
                ],
                default="milking_machine",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="farm",
            field=models.CharField(
                choices=[
                    ("plow", "Plow"),
                    ("harrow", "Harrow"),
                    ("planter", "Planter"),
                    ("tractor", "Tractor"),
                    ("combined harvester", "Combined Harvester"),
                    ("planter", "Planter"),
                    ("hay baler", "Hay-baler"),
                ],
                default="plow",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="poultry",
            field=models.CharField(
                choices=[
                    ("nesting_boxes", "Nesting_boxes"),
                    ("egg_incubators", "Egg_incubators"),
                    ("automatic_waterers", "Automatic_waterers"),
                    ("chicken_coop", "Chicken_coop"),
                    ("brooder_lamp", "Brooder_lamp"),
                ],
                default="nesting_boxes",
                max_length=20,
            ),
        ),
    ]
